# This is a basic workflow to help you get started with Actions

name: Install Next.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install create-next-app
      run: |
        npm install -g create-next-app

    - name: Create Next.js App
      run: |
        npx create-next-app my-next-app --ts --example "https://github.com/vercel/next-learn-starter/tree/master/basics/without-src-and-no-app-router"

    - name: Change Directory
      run: |
        cd my-next-app

    - name: Install Dependencies
      run: |
        npm install firebase mongoose
